typography_spectrum: 0.8071593635249883
color:
  brandStrength: 0.7437506900168955
  lightness: 0.7698352849110961
  saturation: 0.08024826808832586
  rhythmicContrast: 0.04666536953300238
  brandColors:
    - '#FFFFFF'
    - '#22AAE2'
    - '#231F20'
    - '#7B7A7A'
    - '#A4A3A3'
layout_spectrum: 0.18856201181188226
author:
  name: SurAthletics NV
  email: info@surathletics.com
logo: null
name: De Sportwinkel van Letitia Vriesde
title: Do What You Love and Love What You Do
description: Wij zien u graag bij de Sportwinkel van Letitia Vriesde
